apiVersion: v1
kind: Service
metadata:
  name: platformnpservice-srv
spec:
  type: NodePort  # This service type exposes the service on each Node's IP at a static port (the NodePort)  
  selector:
    app: platformservice  # This selector matches the labels in the Deployment
  ports:
    - name: platformservice     # This is the name of the port as it will be referenced in other resources
      protocol: TCP        # Protocol used by the service
      port: 80      # Port that the service will expose
      targetPort: 80    # Port on the container that the service will forward traffic to